### ISSUE TITLE
07-yolov4-tutorial --Darknet Model Conversion Issue

### ISSUE THREAD

**Issue by cq182** [Xilinx/Vitis-AI-Tutorials#47]
when I use the command 'bash scripts/darknet_convert.sh' ,why did I meet this problem?

![image](https://user-images.githubusercontent.com/88963147/150806564-f6c361ce-928e-4c05-819f-0ba4437a789f.png)

if I add sudo before that command,which becomes..

![image](https://user-images.githubusercontent.com/88963147/150807090-b2af1f67-d620-48e8-842b-1251f4069f07.png)

I'm really confused
Thanks for your help!

**Comment by charles-str** [comment]
where the scripts/darknet_convert.sh? why I can't find it?
