### ISSUE TITLE
Python API execute_async multiple outputs

### ISSUE THREAD

**Issue by just-an-intern** [Xilinx/Vitis-AI-Tutorials#73]
Hello,

I am trying to use my compiled CNN model using the Python API and the "dpu.execute_async(inputData,outputData)" function.
However I am not able to recover the output Tensors after using the Runner. My script is based on the MNIST Tutorial [script](https://github.com/Xilinx/Vitis-AI-Tutorials/blob/1.4/Design_Tutorials/09-mnist_pyt/files/application/app_mt.py).
My subgraph has this form:
![image](https://user-images.githubusercontent.com/105802803/173852325-25e32ca8-8a72-4398-b99e-34a66fadbb87.png)
And I have multiple output sizes (after the FPN), I am not sure how to initialize the buffer (as a np.empty() array).

How can I fix this ? 

Thank you for your help.

**Comment by bhargavin1872008** [comment]
when running the requirements.txt  of keras-yolov3-modelset  -i 'm getting error for coremltools.it is showing like "couldn't find a version that satisfies the requirement tensorflow<=1.14 and tensorflow >=1.5(from tfcoremltools -r requirements.txt).(from version :2.2.0,2.2..1, 2.2.2,   ...2.7.0rc0,2.7.0.rc1............) like this .can someone help me regarding this.
                     Also ,i have a doubt .can we use ubuntu 20.04 ,cuda 11.7 ,cudnn 8.4.0 for this project.
                                          or have to use ubuntu 18.04,cuda 10.0 only which only works.please help me regarding this,i have less time in my hand.

**Comment by just-an-intern** [comment]
I found a solution that uses an example design that does exactly this : https://support.xilinx.com/s/article/Multiple-output-model-example-design-from-training-to-application-on-ZCU102?language=en_US
